### PR TITLE
update

### PR DESCRIPTION
**Pull request by aymhce**
## Problem
- *Update available*
- *No default catalog*

## Solution
- *Upgrade to 3.8.6. Fix https://github.com/YunoHost-Apps/ampache_ynh/issues/29*
- *Add a default catalog from /home/yunohost.multimedia/share/Music. Fix https://github.com/YunoHost-Apps/ampache_ynh/issues/30*

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.

## Validation
---
*Minor decision*
- [x] **Upgrade previous version** : Maniack C
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : JimboJoe
- [x] **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/view/Official_fork/job/ampache_ynh%20PR31%20(Official_fork)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
@YunoHost-Apps/apps-group

@aymhce, for next PR, could you please make a branch on this repository then create a pull request  from it ? It's easier for our CI, it can retrieves the branch and make a test by itself.
For this PR, I had to clone the repository by myself, so now it isn't going to be automatically updated.

**Comment by maniackcrudelis** [comment]
Upgrade and code review OK

**Comment by aymhce** [comment]
@maniackcrudelis hello, thanks for review, can I merge it on branch testing ?

**Comment by maniackcrudelis** [comment]
As you can see, we have to wait for a last LGTM. And then wait 3 days before merging.

**Comment by JimboJoe** [comment]
Will be merged in 3 days :wink:

**Pull request merged**
