### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *Update available*
- *No default catalog*

## Solution
- *Upgrade to 3.8.6. Fix https://github.com/YunoHost-Apps/ampache_ynh/issues/29*
- *Add a default catalog from /home/yunohost.multimedia/share/Music. Fix https://github.com/YunoHost-Apps/ampache_ynh/issues/30*

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.

## Validation
---
*Minor decision*
- [x] **Upgrade previous version** : Maniack C from https://github.com/YunoHost-Apps/ampache_ynh/pull/31
- [x] **Code review** : Maniack C from https://github.com/YunoHost-Apps/ampache_ynh/pull/31
- [x] **Approval (LGTM)** : Maniack C from https://github.com/YunoHost-Apps/ampache_ynh/pull/31
- [x] **Approval (LGTM)** : JimboJoe from https://github.com/YunoHost-Apps/ampache_ynh/pull/31
- **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/ampache_ynh%20testing%20(Official)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
@aymhce Could you please create an official forum post (analog to the other ones) so that we could advertise this new release? :wink:

**Comment by aymhce** [comment]
@JimboJoe Hello, this is the new post on forum : https://forum.yunohost.org/t/official-app-ampache/4601

**Comment by Josue-T** [comment]
Hello,
Look good for me.

**Comment by JimboJoe** [comment]
Looks good, thanks!! :heart:

**Comment by maniackcrudelis** [comment]
No modification since #31, so reviews have been taken from this PR.

This PR can be merged in 3 days, if no one want to review it again.

**Pull request merged**
