### PR TITLE
Repair subsonic

### PR DESCRIPTION
**Pull request by billietl**
## Problem
- see #14

## Solution
- Set the rewrite rules regarding the rest endpoint in the __PATH__/rest location

## PR Status
- [X] Code finished.
- [ ] Tested with Package_check.
- [x] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : Kay0u
- **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/ampache_ynh%20PR45%20(Official_fork)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Did anyone have tested that PR ?

**Comment by HugoPoi** [comment]
Tested here, this fix works, can someone merge this because it solve the issue with all subsonic clients for Ampache on Yunohost.

**Comment by maniackcrudelis** [comment]
No one is maintaining this app anymore...
Let's merge in 3 days if no one disagree.

**Comment by anmol26s** [comment]
I will be migrating from Funkwhale to Ampache if its working with Subsonic. Tried to fix this issue last year but was not successful. I will test it tonight.
Thanks

**Pull request merged**
